#ifndef __FRAMEWORK_WSSVCTYPEDEF_H__
#define __FRAMEWORK_WSSVCTYPEDEF_H__

#include "../FWSvcTypeDef.h"

FW_NS_BEGIN

#define FW_WSSVC_SEND_BUF_SIZE		4000
#define FW_WSSVC_RECV_BUF_SIZE		4000
#define FW_WSSVC_SERV_SEND_BUF_SIZE	4000



FW_NS_END


#endif //!__FRAMEWORK_WSSVCTYPEDEF_H__