#ifndef __FRAMEWORK_TCPSVCTYPEDEF_H__
#define __FRAMEWORK_TCPSVCTYPEDEF_H__

#include "../FWSvcTypeDef.h"

FW_NS_BEGIN

#define FW_TCPSVC_SEND_BUF_SIZE	4096
#define FW_TCPSVC_RECV_BUF_SIZE	4096


FW_NS_END


#endif //!__FRAMEWORK_TCPSVCTYPEDEF_H__